"""Printable fake carrier labels for local development and tests."""

from __future__ import annotations

import html
import re

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from backend.core.config import get_settings

router = APIRouter(prefix="/dev-labels", tags=["development"])


@router.get("/{fingerprint}.svg", include_in_schema=False)
async def fake_label(fingerprint: str) -> Response:
    """Render a printable non-production SVG shipping label.

    Args:
        fingerprint: Deterministic fake-provider request fingerprint.

    Returns:
        SVG label clearly marked as non-shippable.

    Raises:
        HTTPException 404: If fake labels are disabled or the key is invalid.
    """
    settings = get_settings()
    if settings.environment == "production" or not re.fullmatch(
        r"[A-F0-9]{18}", fingerprint
    ):
        raise HTTPException(status_code=404, detail="Label not found")
    tracking = html.escape(f"WF{fingerprint}")
    bars = "".join(
        f'<rect x="{40 + index * 6}" y="205" width="{2 + (int(character, 16) % 3)}" height="72" fill="#111"/>'
        for index, character in enumerate(fingerprint)
    )
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400">
<rect width="600" height="400" fill="white"/>
<rect x="12" y="12" width="576" height="376" fill="none" stroke="#111" stroke-width="4"/>
<text x="36" y="58" font-family="Arial, sans-serif" font-size="28" font-weight="700">Whitfield Fulfillment</text>
<text x="36" y="92" font-family="Arial, sans-serif" font-size="18">FakeCarrier - Ground</text>
<line x1="36" y1="112" x2="564" y2="112" stroke="#111" stroke-width="2"/>
<text x="36" y="154" font-family="Arial, sans-serif" font-size="18">DEVELOPMENT LABEL - NOT FOR SHIPMENT</text>
<text x="36" y="190" font-family="monospace" font-size="24" font-weight="700">{tracking}</text>
{bars}
<text x="36" y="322" font-family="monospace" font-size="22">{tracking}</text>
<text x="36" y="362" font-family="Arial, sans-serif" font-size="15">Generated by the local fake carrier adapter</text>
</svg>"""
    return Response(content=svg, media_type="image/svg+xml")
