"""initial_wms_schema

Revision ID: 0fe478e9125e
Revises:
Create Date: 2026-08-13 18:30:59.574933
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0fe478e9125e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("upc", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(op.f("ix_products_upc"), "products", ["upc"], unique=True)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "manager",
                "trusted",
                "staff",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "warehouses",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("name", name=op.f("uq_warehouses_name")),
    )
    op.create_index(op.f("ix_warehouses_code"), "warehouses", ["code"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column(
            "before_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "after_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("request_id", sa.String(length=80), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "web",
                "scanner",
                "voice",
                "automation",
                "api",
                "system",
                name="audit_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_audit_logs_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_actor_created",
        "audit_logs",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_warehouse_id"), "audit_logs", ["warehouse_id"], unique=False
    )
    op.create_index(
        "ix_audit_table_record", "audit_logs", ["table_name", "record_id"], unique=False
    )
    op.create_index(
        "ix_audit_warehouse_created",
        "audit_logs",
        ["warehouse_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_records_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "user_id", "operation", "idempotency_key", name="uq_idempotency_command"
        ),
    )
    op.create_index(
        "ix_idempotency_expiry", "idempotency_records", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_records_user_id"),
        "idempotency_records",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "inbound_receipts",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("tracking_number", sa.String(length=160), nullable=True),
        sa.Column("ticket_number", sa.String(length=160), nullable=True),
        sa.Column("sender_name", sa.String(length=200), nullable=False),
        sa.Column("sender_contact", sa.String(length=200), nullable=True),
        sa.Column("sender_return_address", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "receiving",
                "received",
                "cancelled",
                name="receipt_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("received_by", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nullif(btrim(tracking_number), '') IS NOT NULL OR nullif(btrim(ticket_number), '') IS NOT NULL",
            name=op.f("ck_inbound_receipts_tracking_or_ticket_required"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inbound_receipts_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["users.id"],
            name=op.f("fk_inbound_receipts_received_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inbound_receipts_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_receipts")),
    )
    op.create_index(
        op.f("ix_inbound_receipts_ticket_number"),
        "inbound_receipts",
        ["ticket_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_receipts_tracking_number"),
        "inbound_receipts",
        ["tracking_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_receipts_warehouse_id"),
        "inbound_receipts",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_receipts_warehouse_status_created",
        "inbound_receipts",
        ["warehouse_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "inventory_adjustments",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                name="adjustment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0",
            name=op.f("ck_inventory_adjustments_quantity_delta_nonzero"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inventory_adjustments_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_adjustments_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_adjustments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_adjustments")),
    )
    op.create_index(
        op.f("ix_inventory_adjustments_created_by"),
        "inventory_adjustments",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_adjustments_product_id"),
        "inventory_adjustments",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_adjustments_warehouse_id"),
        "inventory_adjustments",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_balances",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "reserved", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "on_hand >= 0", name=op.f("ck_inventory_balances_on_hand_nonnegative")
        ),
        sa.CheckConstraint(
            "reserved <= on_hand",
            name=op.f("ck_inventory_balances_reserved_not_above_on_hand"),
        ),
        sa.CheckConstraint(
            "reserved >= 0", name=op.f("ck_inventory_balances_reserved_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_balances_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_balances_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_balances")),
        sa.UniqueConstraint(
            "warehouse_id", "product_id", name="uq_inventory_warehouse_product"
        ),
    )
    op.create_index(
        op.f("ix_inventory_balances_product_id"),
        "inventory_balances",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_warehouse_id"),
        "inventory_balances",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_warehouse_updated",
        "inventory_balances",
        ["warehouse_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "OPENING_BALANCE",
                "RECEIPT",
                "RESERVE",
                "RELEASE",
                "SHIP",
                "ADJUST",
                "TRANSFER_OUT",
                "TRANSFER_IN",
                name="movement_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("on_hand_delta", sa.Integer(), nullable=False),
        sa.Column("reserved_delta", sa.Integer(), nullable=False),
        sa.Column("reference_type", sa.String(length=80), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "web",
                "scanner",
                "voice",
                "automation",
                "api",
                "system",
                name="audit_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("on_hand_after", sa.Integer(), nullable=False),
        sa.Column("reserved_after", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_movements_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_movements_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        op.f("ix_inventory_movements_actor_user_id"),
        "inventory_movements",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_product_id"),
        "inventory_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_warehouse_id"),
        "inventory_movements",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_movements_reference",
        "inventory_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_movements_warehouse_created",
        "inventory_movements",
        ["warehouse_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("external_reference", sa.String(length=160), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "allocated",
                "picking",
                "packed",
                "label_created",
                "shipped",
                "cannot_fulfill",
                "cancelled",
                name="order_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
            name=op.f("fk_orders_cancelled_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_orders_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("external_reference", name="uq_order_external_reference"),
    )
    op.create_index(
        op.f("ix_orders_warehouse_id"), "orders", ["warehouse_id"], unique=False
    )
    op.create_index(
        "ix_orders_warehouse_status_created",
        "orders",
        ["warehouse_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_sessions_token_hash")),
    )
    op.create_index(
        "ix_refresh_sessions_user_active",
        "refresh_sessions",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"),
        "refresh_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_warehouse_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_warehouse_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_user_warehouse_assignments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_warehouse_assignments")),
    )
    op.create_index(
        "ix_assignment_warehouse_active",
        "user_warehouse_assignments",
        ["warehouse_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_warehouse_assignments_user_id"),
        "user_warehouse_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_warehouse_assignments_warehouse_id"),
        "user_warehouse_assignments",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "uq_user_active_warehouse_assignment",
        "user_warehouse_assignments",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "warehouse_product_settings",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "low_stock_threshold",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0",
            name=op.f("ck_warehouse_product_settings_low_stock_threshold_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_warehouse_product_settings_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_warehouse_product_settings_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse_product_settings")),
        sa.UniqueConstraint(
            "warehouse_id", "product_id", name="uq_warehouse_product_setting"
        ),
    )
    op.create_index(
        op.f("ix_warehouse_product_settings_product_id"),
        "warehouse_product_settings",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warehouse_product_settings_warehouse_id"),
        "warehouse_product_settings",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inbound_receipt_items",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_received", sa.Integer(), nullable=False),
        sa.Column("quantity_accepted", sa.Integer(), nullable=False),
        sa.Column("quantity_damaged", sa.Integer(), nullable=False),
        sa.Column("damage_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_accepted + quantity_damaged = quantity_received",
            name=op.f("ck_inbound_receipt_items_accepted_damaged_equal_received"),
        ),
        sa.CheckConstraint(
            "quantity_accepted >= 0",
            name=op.f("ck_inbound_receipt_items_quantity_accepted_nonnegative"),
        ),
        sa.CheckConstraint(
            "quantity_damaged >= 0",
            name=op.f("ck_inbound_receipt_items_quantity_damaged_nonnegative"),
        ),
        sa.CheckConstraint(
            "quantity_received > 0",
            name=op.f("ck_inbound_receipt_items_quantity_received_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inbound_receipt_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["inbound_receipts.id"],
            name=op.f("fk_inbound_receipt_items_receipt_id_inbound_receipts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_receipt_items")),
        sa.UniqueConstraint("receipt_id", "product_id", name="uq_receipt_product"),
    )
    op.create_index(
        op.f("ix_inbound_receipt_items_product_id"),
        "inbound_receipt_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inbound_receipt_items_receipt_id"),
        "inbound_receipt_items",
        ["receipt_id"],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_order_items_order_item_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("order_id", "product_id", name="uq_order_product"),
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_product_id"), "order_items", ["product_id"], unique=False
    )
    op.create_table(
        "outbound_packages",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("weight_unit", sa.String(length=12), nullable=False),
        sa.Column("length", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("width", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("height", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("dimension_unit", sa.String(length=12), nullable=False),
        sa.Column("carrier", sa.String(length=80), nullable=True),
        sa.Column("service_level", sa.String(length=80), nullable=True),
        sa.Column("provider_request_id", sa.String(length=160), nullable=True),
        sa.Column("tracking_number", sa.String(length=160), nullable=True),
        sa.Column("label_url_or_key", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "packed",
                "label_created",
                "shipped",
                name="package_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "height > 0", name=op.f("ck_outbound_packages_package_height_positive")
        ),
        sa.CheckConstraint(
            "length > 0", name=op.f("ck_outbound_packages_package_length_positive")
        ),
        sa.CheckConstraint(
            "weight > 0", name=op.f("ck_outbound_packages_package_weight_positive")
        ),
        sa.CheckConstraint(
            "width > 0", name=op.f("ck_outbound_packages_package_width_positive")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_outbound_packages_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_packages")),
        sa.UniqueConstraint(
            "provider_request_id", name=op.f("uq_outbound_packages_provider_request_id")
        ),
        sa.UniqueConstraint(
            "tracking_number", name=op.f("uq_outbound_packages_tracking_number")
        ),
    )
    op.create_index(
        op.f("ix_outbound_packages_order_id"),
        "outbound_packages",
        ["order_id"],
        unique=True,
    )
    op.create_table(
        "damaged_returns",
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_item_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_return",
                "returned_to_sender",
                "cancelled",
                name="damaged_return_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("return_tracking_number", sa.String(length=160), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handled_by", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_damaged_returns_damaged_return_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["handled_by"],
            ["users.id"],
            name=op.f("fk_damaged_returns_handled_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_damaged_returns_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["inbound_receipts.id"],
            name=op.f("fk_damaged_returns_receipt_id_inbound_receipts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_item_id"],
            ["inbound_receipt_items.id"],
            name=op.f("fk_damaged_returns_receipt_item_id_inbound_receipt_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_damaged_returns_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_damaged_returns")),
        sa.UniqueConstraint(
            "receipt_item_id", name=op.f("uq_damaged_returns_receipt_item_id")
        ),
    )
    op.create_index(
        op.f("ix_damaged_returns_product_id"),
        "damaged_returns",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_damaged_returns_receipt_id"),
        "damaged_returns",
        ["receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_damaged_returns_warehouse_id"),
        "damaged_returns",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_damaged_returns_warehouse_status",
        "damaged_returns",
        ["warehouse_id", "status"],
        unique=False,
    )
    op.create_table(
        "inventory_reservations",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "released",
                "consumed",
                name="reservation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0",
            name=op.f("ck_inventory_reservations_reservation_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_inventory_reservations_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_inventory_reservations_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_reservations_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_reservations_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
    )
    op.create_index(
        op.f("ix_inventory_reservations_order_id"),
        "inventory_reservations",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_order_item_id"),
        "inventory_reservations",
        ["order_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_product_id"),
        "inventory_reservations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_warehouse_id"),
        "inventory_reservations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_reservations_order_status",
        "inventory_reservations",
        ["order_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_active_reservation_order_item",
        "inventory_reservations",
        ["order_item_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_reservation_order_item",
        table_name="inventory_reservations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_reservations_order_status", table_name="inventory_reservations")
    op.drop_index(
        op.f("ix_inventory_reservations_warehouse_id"),
        table_name="inventory_reservations",
    )
    op.drop_index(
        op.f("ix_inventory_reservations_product_id"),
        table_name="inventory_reservations",
    )
    op.drop_index(
        op.f("ix_inventory_reservations_order_item_id"),
        table_name="inventory_reservations",
    )
    op.drop_index(
        op.f("ix_inventory_reservations_order_id"), table_name="inventory_reservations"
    )
    op.drop_table("inventory_reservations")
    op.drop_index("ix_damaged_returns_warehouse_status", table_name="damaged_returns")
    op.drop_index(op.f("ix_damaged_returns_warehouse_id"), table_name="damaged_returns")
    op.drop_index(op.f("ix_damaged_returns_receipt_id"), table_name="damaged_returns")
    op.drop_index(op.f("ix_damaged_returns_product_id"), table_name="damaged_returns")
    op.drop_table("damaged_returns")
    op.drop_index(op.f("ix_outbound_packages_order_id"), table_name="outbound_packages")
    op.drop_table("outbound_packages")
    op.drop_index(op.f("ix_order_items_product_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(
        op.f("ix_inbound_receipt_items_receipt_id"), table_name="inbound_receipt_items"
    )
    op.drop_index(
        op.f("ix_inbound_receipt_items_product_id"), table_name="inbound_receipt_items"
    )
    op.drop_table("inbound_receipt_items")
    op.drop_index(
        op.f("ix_warehouse_product_settings_warehouse_id"),
        table_name="warehouse_product_settings",
    )
    op.drop_index(
        op.f("ix_warehouse_product_settings_product_id"),
        table_name="warehouse_product_settings",
    )
    op.drop_table("warehouse_product_settings")
    op.drop_index(
        "uq_user_active_warehouse_assignment",
        table_name="user_warehouse_assignments",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        op.f("ix_user_warehouse_assignments_warehouse_id"),
        table_name="user_warehouse_assignments",
    )
    op.drop_index(
        op.f("ix_user_warehouse_assignments_user_id"),
        table_name="user_warehouse_assignments",
    )
    op.drop_index(
        "ix_assignment_warehouse_active", table_name="user_warehouse_assignments"
    )
    op.drop_table("user_warehouse_assignments")
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_user_active", table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index("ix_orders_warehouse_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_warehouse_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_movements_warehouse_created", table_name="inventory_movements")
    op.drop_index("ix_movements_reference", table_name="inventory_movements")
    op.drop_index(
        op.f("ix_inventory_movements_warehouse_id"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_product_id"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_actor_user_id"), table_name="inventory_movements"
    )
    op.drop_table("inventory_movements")
    op.drop_index("ix_inventory_warehouse_updated", table_name="inventory_balances")
    op.drop_index(
        op.f("ix_inventory_balances_warehouse_id"), table_name="inventory_balances"
    )
    op.drop_index(
        op.f("ix_inventory_balances_product_id"), table_name="inventory_balances"
    )
    op.drop_table("inventory_balances")
    op.drop_index(
        op.f("ix_inventory_adjustments_warehouse_id"),
        table_name="inventory_adjustments",
    )
    op.drop_index(
        op.f("ix_inventory_adjustments_product_id"), table_name="inventory_adjustments"
    )
    op.drop_index(
        op.f("ix_inventory_adjustments_created_by"), table_name="inventory_adjustments"
    )
    op.drop_table("inventory_adjustments")
    op.drop_index("ix_receipts_warehouse_status_created", table_name="inbound_receipts")
    op.drop_index(
        op.f("ix_inbound_receipts_warehouse_id"), table_name="inbound_receipts"
    )
    op.drop_index(
        op.f("ix_inbound_receipts_tracking_number"), table_name="inbound_receipts"
    )
    op.drop_index(
        op.f("ix_inbound_receipts_ticket_number"), table_name="inbound_receipts"
    )
    op.drop_table("inbound_receipts")
    op.drop_index(
        op.f("ix_idempotency_records_user_id"), table_name="idempotency_records"
    )
    op.drop_index("ix_idempotency_expiry", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_audit_warehouse_created", table_name="audit_logs")
    op.drop_index("ix_audit_table_record", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_warehouse_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_warehouses_code"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_upc"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
